"""module1 resume ingestion tables

Creates the four Module 1 tables:
    candidates, resumes, candidate_embeddings, duplicate_tracking
plus the vector extension, the shared updated_at trigger function, every
CHECK constraint, every index (partial, GIN and HNSW) and the triggers.

HAND-WRITTEN, not autogenerated. Alembic autogenerate cannot produce CHECK
constraints, partial indexes, the HNSW index, triggers or comments, so this
file mirrors  backend/app/db/sql/module1/*.sql  line by line instead.

Allowed-value lists are written out as literals on purpose: a migration is
frozen history and must not change when the Python enums change later.

Revision ID: 4f2e9a7c1b3d
Revises: c1a5e0f9b3d2
Create Date: 2026-08-25

NOTE: down_revision was rebased from 8237bb52486e (D-drive repo's chain) to
c1a5e0f9b3d2 (this repo's head, after the voice_interview and email_outreach
migrations) when this file was ported in - see PORT_NOTES.md.

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision = "4f2e9a7c1b3d"
down_revision = "c1a5e0f9b3d2"
branch_labels = None
depends_on = None


def _jsonb_default(literal: str) -> sa.TextClause:
    return sa.text(f"'{literal}'::jsonb")


def upgrade() -> None:
    # ------------------------------------------------------------------
    #  Extension + shared trigger function  (candidates.sql, top)
    # ------------------------------------------------------------------
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    op.execute(
        """
        CREATE OR REPLACE FUNCTION set_updated_at()
        RETURNS TRIGGER AS $$
        BEGIN
            NEW.updated_at = now();
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
        """
    )

    # ------------------------------------------------------------------
    #  1. candidates - the PERSON
    # ------------------------------------------------------------------
    op.create_table(
        "candidates",
        sa.Column("candidate_id", sa.BigInteger(), primary_key=True, autoincrement=True,
                  comment="Primary key, BIGSERIAL. Referenced by every other module. Guessable by design - never use it as a secret."),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=True,
                  comment="Stored lowercase. Unique when present. Primary signal for duplicate detection."),
        sa.Column("phone", sa.String(length=30), nullable=True,
                  comment="Normalised to the last 10 digits only. Secondary signal for duplicate detection."),
        sa.Column("current_location", sa.String(length=255), nullable=True),
        sa.Column("current_job_title", sa.String(length=255), nullable=True),
        sa.Column("current_company", sa.String(length=255), nullable=True),
        sa.Column("experience_years", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("skills", postgresql.JSONB(), nullable=False, server_default=_jsonb_default("[]"),
                  comment='JSON array of skill strings, e.g. ["Java","Docker"]. Query with the @> operator.'),
        sa.Column("education", postgresql.JSONB(), nullable=False, server_default=_jsonb_default("[]")),
        sa.Column("experience", postgresql.JSONB(), nullable=False, server_default=_jsonb_default("[]")),
        sa.Column("certifications", postgresql.JSONB(), nullable=False, server_default=_jsonb_default("[]")),
        sa.Column("linkedin_url", sa.String(length=500), nullable=True),
        sa.Column("extraction_confidence", sa.Numeric(precision=5, scale=2), nullable=True,
                  comment="LLM self-reported confidence, 0.00 to 1.00. Low values mean a human should review."),
        sa.Column("raw_profile_json", postgresql.JSONB(), nullable=True,
                  comment="Complete untouched LLM output, including fields with no column of their own (summary, notice period, languages)."),
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.text("true"),
                  comment="Soft delete flag. Never DELETE a candidate row; set this to FALSE instead."),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),

        sa.CheckConstraint("length(trim(name)) > 0", name="ck_candidates_name_not_blank"),
        sa.CheckConstraint("experience_years IS NULL OR experience_years BETWEEN 0 AND 70",
                           name="ck_candidates_experience_range"),
        sa.CheckConstraint("extraction_confidence IS NULL OR extraction_confidence BETWEEN 0 AND 1",
                           name="ck_candidates_confidence_range"),
        sa.CheckConstraint("email IS NULL OR email = lower(email)", name="ck_candidates_email_lowercase"),
        sa.CheckConstraint("phone IS NULL OR phone ~ '^[0-9]{10}$'", name="ck_candidates_phone_digits"),
        sa.CheckConstraint("jsonb_typeof(skills) = 'array'", name="ck_candidates_skills_is_array"),
        sa.CheckConstraint("jsonb_typeof(education) = 'array'", name="ck_candidates_education_is_array"),
        sa.CheckConstraint("jsonb_typeof(experience) = 'array'", name="ck_candidates_experience_is_array"),
        sa.CheckConstraint("jsonb_typeof(certifications) = 'array'", name="ck_candidates_certifications_is_array"),
        comment="Master candidate profile. One row per human being. Owned by Module 1. Parent of resumes, candidate_embeddings and duplicate_tracking.",
    )

    op.create_index("ux_candidates_email", "candidates", [sa.text("lower(email)")], unique=True,
                    postgresql_where=sa.text("email IS NOT NULL"))
    op.create_index("ix_candidates_phone", "candidates", ["phone"],
                    postgresql_where=sa.text("phone IS NOT NULL"))
    op.create_index("ix_candidates_job_title", "candidates", ["current_job_title"])
    op.create_index("ix_candidates_experience", "candidates", ["experience_years"])
    op.create_index("ix_candidates_location", "candidates", ["current_location"])
    op.create_index("ix_candidates_skills_gin", "candidates", ["skills"], postgresql_using="gin")
    op.create_index("ix_candidates_certifications_gin", "candidates", ["certifications"], postgresql_using="gin")
    op.create_index("ix_candidates_active", "candidates", [sa.text("created_at DESC")],
                    postgresql_where=sa.text("is_active"))

    op.execute(
        """
        CREATE TRIGGER trg_candidates_updated_at
            BEFORE UPDATE ON candidates
            FOR EACH ROW EXECUTE FUNCTION set_updated_at();
        """
    )

    # ------------------------------------------------------------------
    #  2. resumes - the FILES
    # ------------------------------------------------------------------
    op.create_table(
        "resumes",
        sa.Column("resume_id", sa.BigInteger(), primary_key=True, autoincrement=True),
        sa.Column("candidate_id", sa.BigInteger(),
                  sa.ForeignKey("candidates.candidate_id", ondelete="CASCADE"), nullable=True,
                  comment="NULLABLE BY DESIGN. Known only after LLM extraction completes. Set together with resume_version."),
        sa.Column("resume_version", sa.Integer(), nullable=True,
                  comment="Sequential per candidate, starting at 1. Set together with candidate_id."),
        sa.Column("file_name", sa.String(length=500), nullable=False),
        sa.Column("file_path", sa.Text(), nullable=False,
                  comment="Path on local disk where the uploaded file is kept. Local storage only for the POC."),
        sa.Column("file_type", sa.String(length=20), nullable=False),
        sa.Column("file_size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("file_hash", sa.String(length=64), nullable=False,
                  comment="SHA-256 of the raw file bytes, lowercase hex. UNIQUE - this is EXACT_FILE_MATCH enforced by the database."),
        sa.Column("processing_status", sa.String(length=50), nullable=False, server_default="UPLOADED",
                  comment="UPLOADED -> PROCESSING -> EXTRACTED -> COMPLETED, or FAILED / REJECTED. No automatic retries."),
        sa.Column("failure_reason", sa.Text(), nullable=True,
                  comment="Mandatory whenever processing_status is FAILED."),
        sa.Column("extracted_text", sa.Text(), nullable=True,
                  comment="Raw text pulled out of the file by the parser. Input to the LLM extractor and the chunker."),
        sa.Column("is_latest", sa.Boolean(), nullable=False, server_default=sa.text("false"),
                  comment="TRUE for the candidate's current resume. Unique per candidate. Unset the previous row BEFORE setting the new one."),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True,
                  comment="When processing finished (COMPLETED or FAILED). NULL while still in the pipeline."),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),

        sa.CheckConstraint(
            "processing_status IN ('UPLOADED','PROCESSING','EXTRACTED','COMPLETED','FAILED','REJECTED')",
            name="ck_resumes_status"),
        sa.CheckConstraint("file_type IN ('pdf','docx','doc','txt')", name="ck_resumes_file_type"),
        sa.CheckConstraint("file_hash ~ '^[0-9a-f]{64}$'", name="ck_resumes_hash_format"),
        sa.CheckConstraint("file_size_bytes > 0 AND file_size_bytes <= 10485760", name="ck_resumes_size_positive"),
        sa.CheckConstraint("processing_status <> 'FAILED' OR failure_reason IS NOT NULL",
                           name="ck_resumes_failed_has_reason"),
        sa.CheckConstraint(
            "(candidate_id IS NULL AND resume_version IS NULL) "
            "OR (candidate_id IS NOT NULL AND resume_version IS NOT NULL)",
            name="ck_resumes_version_with_candidate"),
        sa.CheckConstraint("is_latest = false OR candidate_id IS NOT NULL", name="ck_resumes_latest_needs_candidate"),
        sa.CheckConstraint("resume_version IS NULL OR resume_version >= 1", name="ck_resumes_version_positive"),
        comment="One row per uploaded resume file. A candidate may have many; exactly one carries is_latest = TRUE. Owned by Module 1.",
    )

    op.create_index("ux_resumes_file_hash", "resumes", ["file_hash"], unique=True)
    op.create_index("ux_resumes_version", "resumes", ["candidate_id", "resume_version"], unique=True,
                    postgresql_where=sa.text("candidate_id IS NOT NULL"))
    op.create_index("ux_resumes_one_latest", "resumes", ["candidate_id"], unique=True,
                    postgresql_where=sa.text("is_latest = true"))
    op.create_index("ix_resumes_candidate", "resumes", ["candidate_id", sa.text("resume_version DESC")])
    op.create_index("ix_resumes_status", "resumes", ["processing_status"])
    op.create_index("ix_resumes_pending", "resumes", ["created_at"],
                    postgresql_where=sa.text("processing_status IN ('UPLOADED','PROCESSING')"))

    op.execute(
        """
        CREATE TRIGGER trg_resumes_updated_at
            BEFORE UPDATE ON resumes
            FOR EACH ROW EXECUTE FUNCTION set_updated_at();
        """
    )

    # ------------------------------------------------------------------
    #  3. candidate_embeddings - the MEANING
    # ------------------------------------------------------------------
    #  ONE row per candidate (the active one): JSONB profile + compact text + vector.
    #  JSONB = the information Module 2 gives the LLM.  VECTOR = what search ranks with.
    op.create_table(
        "candidate_embeddings",
        sa.Column("embedding_id", sa.BigInteger(), primary_key=True, autoincrement=True),
        sa.Column("candidate_id", sa.BigInteger(),
                  sa.ForeignKey("candidates.candidate_id", ondelete="CASCADE"), nullable=False),
        sa.Column("resume_id", sa.BigInteger(),
                  sa.ForeignKey("resumes.resume_id", ondelete="CASCADE"), nullable=False,
                  comment="The exact resume version this vector was generated from. When a newer resume changes the profile, the older row is set is_active = FALSE."),
        sa.Column("profile_metadata", postgresql.JSONB(), nullable=False,
                  comment='The candidate profile as one JSONB object (skills, education, experience, company, phone, ...). Source of truth for what the vector represents; what Module 2 sends to the LLM. Deliberately NOT named "metadata" (reserved by SQLAlchemy).'),
        sa.Column("embedding_text", sa.Text(), nullable=False,
                  comment="profile_metadata rendered as compact text - the exact input the embedding model read. NEVER drop this column: a vector cannot be turned back into text."),
        sa.Column("embedding", Vector(768), nullable=False,
                  comment="VECTOR(768) produced by nomic-embed-text from embedding_text. Changing the embedding model invalidates every row."),
        sa.Column("model_name", sa.String(length=100), nullable=False,
                  comment="Embedding model that produced this vector. Vectors from different models are not comparable."),
        sa.Column("model_version", sa.String(length=50), nullable=True),
        sa.Column("content_hash", sa.String(length=64), nullable=False,
                  comment="SHA-256 of embedding_text. Same hash and same model on re-upload means the profile did not change, so the embedding is not regenerated."),
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.text("true"),
                  comment="TRUE on exactly one row per candidate. FALSE means superseded by a newer resume version. Search must filter on is_active to use the HNSW index."),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),

        sa.CheckConstraint("length(trim(embedding_text)) > 0", name="ck_emb_text_not_blank"),
        sa.CheckConstraint("content_hash ~ '^[0-9a-f]{64}$'", name="ck_emb_content_hash_format"),
        sa.CheckConstraint("length(trim(model_name)) > 0", name="ck_emb_model_name_not_blank"),
        sa.CheckConstraint("jsonb_typeof(profile_metadata) = 'object'", name="ck_emb_metadata_is_object"),
        comment="One semantic vector per candidate (one active row each) plus the JSONB profile it was built from. Owned by Module 1, queried by Module 2 for Top-K candidate retrieval.",
    )

    #  One resume version produces at most one vector.
    op.create_index("ux_emb_resume", "candidate_embeddings", ["resume_id"], unique=True)
    #  Exactly one LIVE vector per candidate. Also serves the "this candidate's live row" lookup.
    op.create_index("ux_emb_candidate_active", "candidate_embeddings", ["candidate_id"], unique=True,
                    postgresql_where=sa.text("is_active"))
    #  THE SEARCH INDEX: HNSW, cosine distance, active rows only.
    op.create_index(
        "ix_emb_hnsw", "candidate_embeddings", ["embedding"],
        postgresql_using="hnsw",
        postgresql_with={"m": 16, "ef_construction": 64},
        postgresql_ops={"embedding": "vector_cosine_ops"},
        postgresql_where=sa.text("is_active"),
    )

    op.execute(
        """
        CREATE TRIGGER trg_emb_updated_at
            BEFORE UPDATE ON candidate_embeddings
            FOR EACH ROW EXECUTE FUNCTION set_updated_at();
        """
    )

    # ------------------------------------------------------------------
    #  4. duplicate_tracking - the DIARY  (append-only: no updated_at, no trigger)
    # ------------------------------------------------------------------
    op.create_table(
        "duplicate_tracking",
        sa.Column("duplicate_id", sa.BigInteger(), primary_key=True, autoincrement=True),
        sa.Column("resume_id", sa.BigInteger(),
                  sa.ForeignKey("resumes.resume_id", ondelete="CASCADE"), nullable=True,
                  comment="The incoming resume that triggered this event. NULL for an EXACT_FILE_MATCH rejection caught before any resumes row existed."),
        sa.Column("candidate_id", sa.BigInteger(),
                  sa.ForeignKey("candidates.candidate_id", ondelete="SET NULL"), nullable=True,
                  comment="The candidate the incoming resume was attached to. NULL when the upload was rejected."),
        sa.Column("matched_candidate_id", sa.BigInteger(),
                  sa.ForeignKey("candidates.candidate_id", ondelete="SET NULL"), nullable=True,
                  comment="The pre-existing candidate that was matched."),
        sa.Column("matched_resume_id", sa.BigInteger(),
                  sa.ForeignKey("resumes.resume_id", ondelete="SET NULL"), nullable=True),
        sa.Column("matched_embedding_id", sa.BigInteger(),
                  sa.ForeignKey("candidate_embeddings.embedding_id", ondelete="SET NULL"), nullable=True,
                  comment="The candidate_embeddings row whose vector was similar. Populated only for SEMANTIC_MATCH."),
        sa.Column("duplicate_type", sa.String(length=50), nullable=False,
                  comment="EXACT_FILE_MATCH / EMAIL_MATCH / PHONE_MATCH / SEMANTIC_MATCH (never auto-merged)."),
        sa.Column("duplicate_confidence", sa.Numeric(precision=5, scale=2), nullable=True,
                  comment="0.00 to 1.00. Exact matches record 1.00. Mandatory for SEMANTIC_MATCH."),
        sa.Column("action_taken", sa.String(length=100), nullable=False,
                  comment="What the system actually did. MANUAL_REVIEW_REQUIRED is reserved for a future workflow."),
        sa.Column("detection_details", postgresql.JSONB(), nullable=False, server_default=_jsonb_default("{}"),
                  comment='Evidence object, e.g. {"matched_on":"email","value":"ravi.kumar@gmail.com"}.'),
        sa.Column("old_raw_profile_json", postgresql.JSONB(), nullable=True,
                  comment="The candidate's profile BEFORE this event. The undo button. Never empty on a PROFILE_UPDATED row."),
        sa.Column("new_raw_profile_json", postgresql.JSONB(), nullable=True,
                  comment="The candidate's profile AFTER this event."),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),

        sa.CheckConstraint(
            "duplicate_type IN ('EXACT_FILE_MATCH','EMAIL_MATCH','PHONE_MATCH','SEMANTIC_MATCH')",
            name="ck_dup_type"),
        sa.CheckConstraint(
            "action_taken IN ('NEW_CANDIDATE_CREATED','RESUME_APPENDED','PROFILE_UPDATED',"
            "'DUPLICATE_REJECTED','MANUAL_REVIEW_REQUIRED')",
            name="ck_dup_action"),
        sa.CheckConstraint("duplicate_confidence IS NULL OR duplicate_confidence BETWEEN 0 AND 1",
                           name="ck_dup_confidence_range"),
        sa.CheckConstraint("duplicate_type <> 'SEMANTIC_MATCH' OR duplicate_confidence IS NOT NULL",
                           name="ck_dup_semantic_needs_confidence"),
        sa.CheckConstraint(
            "matched_candidate_id IS NOT NULL OR matched_resume_id IS NOT NULL OR matched_embedding_id IS NOT NULL",
            name="ck_dup_matched_something"),
        sa.CheckConstraint("jsonb_typeof(detection_details) = 'object'", name="ck_dup_details_is_object"),
        comment="Append-only audit log of duplicate detection events. Evidence only - drives no behaviour. Owned by Module 1.",
    )

    op.create_index("ix_dup_candidate", "duplicate_tracking", ["candidate_id"],
                    postgresql_where=sa.text("candidate_id IS NOT NULL"))
    op.create_index("ix_dup_matched_candidate", "duplicate_tracking", ["matched_candidate_id"],
                    postgresql_where=sa.text("matched_candidate_id IS NOT NULL"))
    op.create_index("ix_dup_resume", "duplicate_tracking", ["resume_id"])
    op.create_index("ix_dup_review_queue", "duplicate_tracking", ["created_at"],
                    postgresql_where=sa.text("action_taken = 'MANUAL_REVIEW_REQUIRED'"))
    op.create_index("ix_dup_type", "duplicate_tracking", ["duplicate_type"])
    op.create_index("ix_dup_created", "duplicate_tracking", [sa.text("created_at DESC")])
    #  No updated_at trigger on this table - intentional. Rows are never updated.


def downgrade() -> None:
    #  Reverse order of creation: children first, then parents.
    #  Dropping a table drops its indexes, constraints and triggers with it.
    op.drop_table("duplicate_tracking")
    op.drop_table("candidate_embeddings")
    op.drop_table("resumes")
    op.drop_table("candidates")

    op.execute("DROP FUNCTION IF EXISTS set_updated_at()")

    #  The vector extension is deliberately NOT dropped: infra/postgres/init.sql
    #  creates it at database birth, and dropping it here would surprise anyone
    #  who runs downgrade on a shared database.
