"""inital table creation

Revision ID: a48fa005ea59
Revises: a40dfd7064b0
Create Date: 2026-08-20 18:21:00.763447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a48fa005ea59'
down_revision = 'a40dfd7064b0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
