"""inital table creation

Revision ID: de2cfd90936f
Revises: a48fa005ea59
Create Date: 2026-08-20 18:21:39.261321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de2cfd90936f'
down_revision = 'a48fa005ea59'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
